# [target.x86_64-pc-windows-msvc]
# rustflags = ["-Ctarget-feature=+crt-static"]
# [target.i686-pc-windows-msvc]
# rustflags = ["-Ctarget-feature=+crt-static"]
# [target.x86_64-uwp-windows-msvc]
# rustflags = ["-Ctarget-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = [
  # Set up delayloads.
  "-C", "link-args=dloadhelper.lib /delayload:ws2_32.dll /delayload:virtdisk.dll /delayload:user32.dll",
  # Set up the CRT: use ucrtbase.dll but statically link the VC runtime.
  "-C", "link-args=/nodefaultlib onecore_apiset.lib ucrt.lib libvcruntime.lib libcmt.lib",
  ## "-Z", "print-link-args",
]
